language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install gTTS
  - pip install pygame
# command to run tests
script:
  - python gTTSwrapper.py
